"use client";

import "../globals.css"
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import {
  AuthContext,
  AuthDispatchContext,
  initialUserState,
  userReducer,
} from "./AuthContext";
import { useEffect, useReducer, useState } from "react";
import {
  browserLocalPersistence,
  onAuthStateChanged,
  setPersistence,
} from "firebase/auth";
import { auth } from "@/firebase.config";
import Loading from "@/components/Loading";
import MainContainer from "@/components/MainContainer";
import Intro from "@/components/Intro";

const figtree = Figtree({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [currentUser, dispatch] = useReducer(userReducer, initialUserState);
  const [isLoading, setLoading] = useState(true);
  setPersistence(auth, browserLocalPersistence);

  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        dispatch({ type: "LOGIN", payload: user });
        setLoading(false);
      } else {
        dispatch({ type: "LOGOUT", payload: null });
        setLoading(false);
      }
    });
  });

  return (
    <AuthContext.Provider value={currentUser}>
      <AuthDispatchContext.Provider value={dispatch}>
        <html lang="en">
          <body
            className={`flex flex-col items-center bg-black px-4 p-8 antialiased font-medium ${figtree.className}`}
          >
            {isLoading ? (
              <Loading />
            ) : (
              <MainContainer>
                <Intro />
                {children}
              </MainContainer>
            )}
          </body>
        </html>
      </AuthDispatchContext.Provider>
    </AuthContext.Provider>
  );
}
